export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST";
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_USER_LOGOUT = "PARENT_USER_LOGOUT";

export const DOCTOR_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const DOCTOR_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const DOCTOR_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
export const DOCTOR_DETAILS_RESET = "DOCTOR_DETAILS_RESET";

export const DOCTOR_UPDATE_REQUEST = "DOCTOR_UPDATE_REQUEST";
export const DOCTOR_UPDATE_SUCCESS = "DOCTOR_UPDATE_SUCCESS";
export const DOCTOR_UPDATE_FAIL = "DOCTOR_UPDATE_FAIL";
export const DOCTOR_UPDATE_RESET = "DOCTOR_UPDATE_RESET";

export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST ";
export const GET_DOCTORS_SUCCESS = " GET_DOCTORS_SUCCESS";
export const GET_DOCTORS_FAIL = "GET_DOCTORS_FAIL";

export const LIST_DOCTORS_REQUEST = "LIST_DOCTORS_REQUEST ";
export const LIST_DOCTORS_SUCCESS = " LIST_DOCTORS_SUCCESS";
export const LIST_DOCTORS_FAIL = "LIST_DOCTORS_FAIL";



export const GET_DOCTOR_REQUEST = "GET_DOCTOR_REQUEST ";
export const GET_DOCTOR_SUCCESS = " GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_FAIL = "GET_DOCTOR_FAIL";
