export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_LOGIN_FAIL = "PATIENT_LOGIN_FAIL";
export const PATIENT_USER_LOGOUT = "PATIENT_USER_LOGOUT";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";
export const PATIENT_DETAILS_RESET = "PATIENT_DETAILS_RESET";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_UPDATE_FAIL = "PATIENT_UPDATE_FAIL";
export const PATIENT_UPDATE_RESET = "PATIENT_UPDATE_RESET";

export const GET_PATIENTS_REQUEST = "GET_PATIENTS_REQUEST";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";

export const LIST_PATIENTS_REQUEST = "LIST_PATIENTS_REQUEST";
export const LIST_PATIENTS_SUCCESS = "LIST_PATIENTS_SUCCESS";
export const LIST_PATIENTS_FAIL = "LIST_PATIENTS_FAIL";

export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENT_FAIL = "GET_PATIENT_FAIL";

export const BOOKMARK_DOCTOR_REQUEST = "BOOKMARK_DOCTOR_REQUEST";
export const BOOKMARK_DOCTOR_SUCCESS = "BOOKMARK_DOCTOR_SUCCESS ";
export const BOOKMARK_DOCTOR_FAIL = "BOOKMARK_DOCTOR_FAIL";
export const BOOKMARK_DOCTOR_RESET = "BOOKMARK_DOCTOR_RESET";

